version: '3.7'
volumes:
  mysql_data:
    driver: local

services:
  sut:
    build:
      context: .
      dockerfile: docker-hub/Dockerfile
    command: "/app/run_tests.sh"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KEYCLOAK_URL: "http://keycloak:8080"
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "Pa55w0rd"
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: "true"
      IMPORT_PATH: "/config"
      IMPORT_FORCE: "true"
  proxy:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      HOST_HEADER: protected-site
      PROXY_TO: http://protected-site:8080/
      REALM_NAME: master
      AUTH_SERVER: http://keycloak:8080/auth/
      CLIENT_ID: basic-auth-service
      CLIENT_SECRET: password
    depends_on:
      - keycloak
      - mysql
      - protected-site
  protected-site:
    image: bitnami/chartmuseum
    ports:
      - 8082:8080
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command:
      - "-c"
      - "standalone.xml"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "connectTimeout=30000"
    ports:
      - 8081:8080
    depends_on:
      - mysql

