name: Release

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker Build
        run: make image
      - name: Docker Test
        run: make test
      - name: Docker Push
        run: make push
      - name: Create Output Version
        id: release
        run: |
          export VERSION=$(cat VERSION)
          echo ::debug ::relase version ${VERSION}
          echo ::set-output name=tag_name::v${VERSION}
      - name: Update version
        id: updatev
        run: |
          git config user.name  github-actions
          git config user.email github-actions@github.com
          git add VERSION
          git commit -m "bump version"
          git push
          curl --request POST \
               --url https://api.github.com/repos/${{ github.repository }}/releases \
               --header "Accept: application/vnd.github.v3+json" \
               --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
               --header 'content-type: application/json' \
               --data '{
                   "tag_name": "${{ steps.release.outputs.tag_name }}",
                   "body": "docker pull rafaelcalleja/jetty-proxy-keycloak:${{ steps.release.outputs.tag_name }}",
                   "name": "Release ${{ steps.release.outputs.tag_name }}",
                   "draft": false,
                   "prerelease": false
               }'
          exit $?
